[[redirects]]
  from = "/shop/*"
  to = "https://shopify.tbntdima.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = '/sergey/*'
  to = "https://sergeyan.netlify.app/:splat"
  status = 200
  force = true